backend:
  name: git-gateway
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "page"
    label: "Pages"
    files:
      - file: "src/content/landing-content.md"
        label: "Landing Page"
        name: "landingPage"
        fields:
          - { label: Heading, name: heading, widget: string }
          - { label: Subtext, name: subtext, widget: text }
      - file: "src/content/contact-info.md"
        label: "Contact Info Page"
        name: "contactpage"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Address1, name: address1, widget: string }
          - { label: Address2, name: address2, widget: string }
          - { label: City, name: city, widget: string }
          - { label: State, name: state, widget: string }
          - { label: ZipCode, name: zipCode, widget: number }
          - { label: eMail, name: eMail, widget: string }
          - { label: "Telephone Number", name: telphone, widget: string }

  - name: menus
    label: Menus
    folder: "src/content/menus"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Name, name: name, widget: string }
      - { label: Description, name: description, widget: text, required: false }
      - {
          label: Hours,
          name: hours,
          widget: list,
          fields:
            [
              {
                label: From,
                name: from,
                widget: datetime,
                dateFormat: false,
                format: "HH:MM",
              },
              {
                label: To,
                name: to,
                widget: datetime,
                dateFormat: false,
                format: "HH:MM",
              },
            ],
        }

  - name: sides
    label: Sides
    folder: "src/content/fooditem"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Name, name: name, widget: string, required: true }
      - { label: Description, name: description, widget: text }
      - { label: Price, name: price, widget: number }
      
  - name: dishes
    label: Dishes
    folder: "src/content/fooditem"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Name, name: name, widget: string, required: true }
      - { label: Description, name: description, widget: text }
      - { label: Price, name: price, widget: number } 
      - { label: Sides, name: sidedishes, widget: relation, collection: sides, valueField: name, searchFields: ["name"], multiple: true }
      - { label: "Menus", name: membermenus, widget: relation, collection: menus, valueField: name, searchFields: ["name"], multiple: true }

  - name: drinks
    label: Drinks
    folder: "src/content/fooditem"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Name, name: name, widget: string, required: true }
      - { label: Description, name: description, widget: text }
      - { label: Price, name: price, widget: number }
      - { label: "Member Menu", name: menumember, widget: relation, collection: menus, valueField: name, searchFields: ["name"], multiple: true }
